version: "3.9"

services:
  app:
    build: .
    container_name: ai_social_app
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  worker:
    build: .
    container_name: ai_social_worker
    command: celery -A workers.celery_app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: ai_social_redis
    restart: always

  db:
    image: postgres:15
    container_name: ai_social_db
    environment:
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      POSTGRES_DB: ai_social
    ports:
      - "5432:5432"
    restart: always
